import Header from "@/components/header";
import "./globals.css";
import {Inter} from "next/font/google"
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";

const inter = Inter({subsets:['latin']})
 


export const metadata = {
  title: "Smart Spend",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${inter.className} bg-primary-white`}
      >
        {/* header */}
        <Header/>
        <main className="min-h-screen ">{children}</main>
        <Toaster richColors/>
        {/* footer */}
        <footer className="bg-green-100 p-5">
          <div className="container mx-auto text-center text-gray-600 ">
            <p>Developed by SAM :)</p>
          </div>
        </footer>
      </body>

    </html>
    </ClerkProvider>
  );
}
